#define ERROR 1
#define CONSTANT 2
#define INT 3
#define FLOAT 4
#define STRING 5
#define CHAR 6
#define BOOL 7
#define IF 8					 
#define THEN 9				
#define ELSE 10				
#define WHILE 11			
#define DO 12					 
#define SWITCH 13	
#define CASE 14				
#define DEFAULT 15	
#define FOR 16		   
#define AND 17	 	   
#define OR 18			   
#define EQUALEQUAL 19		 
#define GREATERTHAN 20
#define SMALLERTHAN 21
#define GREATERTHANOREQUAL 22
#define SMALLERTHANOREQUAL 23
#define INTVALUE 24
#define FLOATVALUE 25
#define STRINGVALUE 26
#define CHARVALUE 27
#define BOOLVALUE 28
#define IDENTIFIER 29
#define OPENED_BRACKET 30
#define SEMI_COLON 31
#define CLOSED_BRACKET 32
#define OPENED_BRACE 33
#define CLOSED_BRACE 34
#define OPENED_SQ_BRACKET 35
#define CLOSED_SQ_BRACKET 36
#define COMMA 37
#define TWO_DOTS 38
#define PLUS 39
#define MINUS 40
#define MULTIPLY 41
#define DIVIDE 42
#define REMAINDER 43
#define PLUS_EQUAL 44
#define MINUS_EQUAL 45
#define MULTIPLY_EQUAL 46
#define DIVIDE_EQUAL 47
#define PLUS_PLUS 48
#define MINUS_MINUS 49
#define EQUAL 50
#define NOT 51
#define NOTEQUAL 52