#define INTVALUE 1
#define CONSTANT 2
#define INT 3
#define FLOAT 4
#define STRING 5
#define CHAR 6
#define BOOL 7
#define IF 8					 
#define THEN 9				
#define ELSE 10				
#define WHILE 11			
#define DO 12					 
#define SWITCH 13	
#define CASE 14				
#define DEFAULT 15	
#define FOR 16		   
#define AND 17	 	   
#define OR 18			   
#define EQUAL 19		 
#define GREATERTHAN 20
#define SMALLERTHAN 21
#define GREATERTHANOREQUAL 22
#define SMALLERTHANOREQUAL 23
#define FLOATVALUE 24
#define STRINGVALUE 25
#define CHARVALUE 26
#define BOOLVALUE 27
#define IDENTIFIER 28